apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "srtsignin"
  annotations: 
    ingress.kubernetes.io/rewrite-target: /
    ingress.kubernetes.io/enable-cors: "true"
    ingress.kubernetes.io/cors-allow-headers: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,AuthToken,RosefireToken"
  namespace: default
spec:
  tls:
  - secretName: srtsignin-certs
  rules:
  - host: srtsign.in
    http:
      paths:
      - path: /api/data
        backend:
          serviceName: srtsignin-data-service
          servicePort: 80
      - path: /api/cardfire
        backend:
          serviceName: srtsignin-cardfire
          servicePort: 80
      - path: /api/role
        backend:
          serviceName: srtsignin-role-service
          servicePort: 80
      - path: /api/active
        backend:
          serviceName: srtsignin-active-user-service
          servicePort: 80
      - path: /api/register
        backend:
          serviceName: srtsignin-registration-service
          servicePort: 80
      - path: /
        backend:
          serviceName: srtsignin-web-app-service
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "srtsignin"
  annotations: 
    ingress.kubernetes.io/rewrite-target: /
    ingress.kubernetes.io/enable-cors: "true"
    ingress.kubernetes.io/cors-allow-headers: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,AuthToken"
  namespace: stage
spec:
  tls:
  - secretName: srtsignin-certs
  rules:
  - host: stage.srtsign.in
    http:
      paths:
      - path: /api/data
        backend:
          serviceName: srtsignin-data-service
          servicePort: 80
      - path: /api/cardfire
        backend:
          serviceName: srtsignin-cardfire
          servicePort: 80
      - path: /api/role
        backend:
          serviceName: srtsignin-role-service
          servicePort: 80
      - path: /api/active
        backend:
          serviceName: srtsignin-active-user-service
          servicePort: 80
      - path: /
        backend:
          serviceName: srtsignin-web-app-service
          servicePort: 80
