---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: srtsignin-web-app
  annotations:
    flux.weave.works/automated: 'true'
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: srtsignin-web-app
    spec:
      containers:
      - name: web-app
        image: 'cjblink1/srtsignin-web-app:23ceaa1d09da7e20d67867b0062433e07ba67f36'
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: srtsignin-web-app-service
  labels:
    name: srtsignin-web-app-service
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: srtsignin-web-app
  type: ClusterIP
