apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: srtsignin
  annotations: ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - secretName: srtsignin-certs
  rules:
  - host: srtsign.in
    http:
      paths:
      - path: /
        backend:
          serviceName: srtsignin-web-app-service
          servicePort: 80
      - path: /api/role
        backend:
          serviceName: srtsignin-role-service
          servicePort: 80
