apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: srtsignin-certificate
  namespace: default
spec:
  secretName: srtsignin-certs
  issuerRef:
    name: letsencrypt-prod-cluster-issuer
    kind: ClusterIssuer
  commonName: srtsign.in
  dnsNames:
  - srtsign.in
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - srtsign.in
